### ISSUE TITLE
Create repos/packages for all the new elements

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/polymer-dart#533]
- [x] Iron Elements [catalog](https://elements.polymer-project.org/browse?package=iron-elements), [issue](https://github.com/dart-lang/polymer-dart/issues/541)
- [x] Paper Elements [catalog](https://elements.polymer-project.org/browse?package=paper-elements), [issue](https://github.com/dart-lang/polymer-dart/issues/542)
- [x] Google Web Components [catalog](https://elements.polymer-project.org/browse?package=google-web-components), [issue](https://github.com/dart-lang/polymer-dart/issues/543)
- [x] Gold Elements  [catalog](https://elements.polymer-project.org/browse?package=gold-elements), [issue](https://github.com/dart-lang/polymer-dart/issues/544)
- [x] Neon Elements  [catalog](https://elements.polymer-project.org/browse?package=neon-elements), [issue](https://github.com/dart-lang/polymer-dart/issues/545)
- [x] Platinum Elements  [catalog](https://elements.polymer-project.org/browse?package=platinum-elements), [issue](https://github.com/dart-lang/polymer-dart/issues/546)
- [x] Molecules  [catalog](https://elements.polymer-project.org/browse?package=molecules), [issue](https://github.com/dart-lang/polymer-dart/issues/547)

**Comment by jakemac53** [comment]
These should also only have a `polymer_interop` dependency if possible.

**Comment by jakemac53** [comment]
blocked on https://github.com/dart-lang/custom-element-apigen/issues/29

**Comment by jakemac53** [comment]
Ended up creating just one repo/package for all of these, pushed to github https://github.com/dart-lang/polymer_elements but not yet published. Also still needs tests/verification, but I will create separate bugs for that.
